### ISSUE TITLE
Some suggestions...

### ISSUE THREAD

**Issue by balthild** [zdy1988/Zhai.PictureView#1]
This is a great project! Other open source image viewers are basically ugly...

Here's some suggestions:

1. Provide an option to enable/disable the translucent window background.
2. According to the usual custom, 100% zoom level should corresponds to the "original size" view mode rather than "fit window".
3. Provide a x64 build.

**Comment by zdy1988** [comment]
hi，感谢你的关注

谢谢你的几个建议
1.我准备弄一个背景调整透明度和颜色的功能
2.也许我把图标换一换就行了
3.现在的Releases版本就是64位的！

**Comment by zdy1988** [comment]
第二个问题，我感觉是你把我原图的显示逻辑弄反了

**Comment by balthild** [comment]
> 第二个问题，我感觉是你把我原图的显示逻辑弄反了

应该不是吧，参见以下截图，我打开的这张图片是一张很大的壁纸（尺寸是 4600x4600），但是当它缩放到适合窗口大小时，提示的缩放比是 100%。

![image](https://user-images.githubusercontent.com/2662758/206119133-2df151be-0053-42fb-ae74-d34a61b378a9.png)

**Comment by zdy1988** [comment]
对，100%就是适应屏幕，你点击 *1:1* 就是原图大小

**Comment by balthild** [comment]
这个问题并不涉及下面工具栏里那个在「1:1」和「适应屏幕」之间切换的按钮，因为用鼠标滚轮也可以缩放图片并看到缩放百分比的提示。

我想说的问题是，按照一般图片浏览器的习惯，应该让 100% 对应原图大小的缩放等级吧，比如 Windows 10 自带的图片浏览器就是这样。
